In [7]:
import pandas as pd

In [8]:
df=pd.read_csv ("C:/Users/kalai yarasan/OneDrive/Desktop/new project/Shopping_Trends_And_Customer_Behaviour.csv")

In [9]:
df.head()

,Unnamed: 0,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,0,1,55,Male,Blouse,Clothing,53,Kentucky,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,1,2,19,Male,Sweater,Clothing,64,Maine,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,2,3,50,Male,Jeans,Clothing,73,Massachusetts,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,3,4,21,Male,Sandals,Footwear,90,Rhode Island,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,4,5,45,Male,Blouse,Clothing,49,Oregon,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              3900 non-null   int64
 1   Customer ID             3900 non-null   int64
 2   Age                     3900 non-null   int64
 3   Gender                  3900 non-null   object
 4   Item Purchased          3900 non-null   object
 5   Category                3900 non-null   object
 6   Purchase Amount (USD)   3900 non-null   int64
 7   Location                3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(5), object(12)
memory usage: 548.6+ KB

In [11]:
df.describe()

,Unnamed: 0,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1949.500000,1950.500000,44.068462,59.764359,3.749443,25.351538
std,1125.977353,1125.977353,15.207589,23.685392,0.716387,14.447125
min,0.000000,1.000000,18.000000,20.000000,2.500000,1.000000
25%,974.750000,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1949.500000,1950.500000,44.000000,60.000000,3.700000,25.000000
75%,2924.250000,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3899.000000,3900.000000,70.000000,100.000000,5.000000,50.000000

In [12]:
df.describe(include="all")

,Unnamed: 0,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,NaN,2,25,4,NaN,50,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,NaN,2652,171,1737,NaN,96,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1949.500000,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,3.749443,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,0.716387,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,0.000000,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,974.750000,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1949.500000,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2924.250000,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3899.000000,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [13]:
df.isnull().sum()

Unnamed: 0                 0
Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [14]:
df["Review Rating"] =df.groupby("Category")["Review Rating"].transform(lambda x: x.fillna(x.median()))

In [15]:
df.isnull().sum()

Unnamed: 0                0
Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [16]:
df.columns = df.columns.str.lower()
df.columns =df.columns.str.replace(" ","_")
df=df.rename(columns={"purchase_amount_(usd)":"purchase_amount"})

In [17]:
df.columns

Index(['unnamed:_0', 'customer_id', 'age', 'gender', 'item_purchased',
       'category', 'purchase_amount', 'location', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [18]:
upmeta= ["young Adult","Adult","Middle Age","Senior"]
df["age_group"]= pd.qcut(df["age"] ,q=4,labels=upmeta)

In [19]:
df[["age" ,"age_group"]].head(10)

   age    age_group
0   55   Middle Age
1   19  young Adult
2   50   Middle Age
3   21  young Adult
4   45   Middle Age
5   46   Middle Age
6   63       Senior
7   27  young Adult
8   26  young Adult
9   57   Middle Age

In [20]:
df["frequency_of_purchases"].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [21]:
mapping= {
    'Fortnightly' :14,
    'Weekly':7,
    'Annually':365,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Monthly':30,
    'Every 3 Months':90
}
df["purchases_recent"]=df["frequency_of_purchases"].map(mapping)

In [22]:
df[["purchases_recent" , "frequency_of_purchases"]].head(25)

    purchases_recent frequency_of_purchases
0                 14            Fortnightly
1                 14            Fortnightly
2                  7                 Weekly
3                  7                 Weekly
4                365               Annually
5                  7                 Weekly
6                 90              Quarterly
7                  7                 Weekly
8                365               Annually
9                 90              Quarterly
10                14              Bi-Weekly
11                14            Fortnightly
12                14            Fortnightly
13                 7                 Weekly
14                 7                 Weekly
15                30                Monthly
16                14              Bi-Weekly
17                90              Quarterly
18                 7                 Weekly
19                14              Bi-Weekly
20                90         Every 3 Months
21                90              Quarterly
22               365               Annually
23                 7                 Weekly
24                 7                 Weekly

In [23]:
(df["discount_applied"]== df["promo_code_used"]).all()

np.True_

In [24]:
df=df.drop("promo_code_used" ,axis=1)

In [25]:
df.columns

Index(['unnamed:_0', 'customer_id', 'age', 'gender', 'item_purchased',
       'category', 'purchase_amount', 'location', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchases_recent'],
      dtype='object')

In [26]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\kalai yarasan\appdata\local\programs\python\python314\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\kalai yarasan\appdata\local\programs\python\python314\lib\site-packages (2.0.46)
Requirement already satisfied: greenlet>=1 in c:\users\kalai yarasan\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (3.3.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\kalai yarasan\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\kalai yarasan\AppData\Local\Programs\Python\Python314\python.exe -m pip install --upgrade pip

In [27]:
pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\kalai yarasan\appdata\local\programs\python\python314\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\kalai yarasan\appdata\local\programs\python\python314\lib\site-packages (2.0.46)
Requirement already satisfied: greenlet>=1 in c:\users\kalai yarasan\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (3.3.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\kalai yarasan\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\kalai yarasan\AppData\Local\Programs\Python\Python314\python.exe -m pip install --upgrade pip

In [30]:
from sqlalchemy import create_engine
username="root"
password="2611"
host="localhost"
port="3306"
database="mydatabase"
engine = create_engine (f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

table_name ="mytable" 
df.to_sql(table_name,engine,if_exists="replace", index=False)

pd.read_sql("SELECT * FROM mytable LIMIT 5;", engine)

,unnamed:_0,customer_id,age,gender,item_purchased,category,purchase_amount,location,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchases_recent
0,0,1,55,Male,Blouse,Clothing,53,Kentucky,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle Age,14
1,1,2,19,Male,Sweater,Clothing,64,Maine,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,young Adult,14
2,2,3,50,Male,Jeans,Clothing,73,Massachusetts,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle Age,7
3,3,4,21,Male,Sandals,Footwear,90,Rhode Island,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,young Adult,7
4,4,5,45,Male,Blouse,Clothing,49,Oregon,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle Age,365